config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create'
  
  get '/upload', to:"microposts#new"
  get  '/signup',  to: 'users#new'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
   member do
    get :following, :followers
    end
  end
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts do
   resources :likes, only: [:new, :create, :destory]
   resources :comments, only: [:index, :create, :destroy], shallow: true
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
   def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
   end
end

app/views/application/_comment_list.html.erb
<% micropost.comments.each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "", comment_path(comment), method: :delete, remote: true, class: "delete-comment" %>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration black-color" %>
      </strong>
    </span>
    <span><%= comment.comment %></span>
  </div>
<% end %>