config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create'
  
  get '/upload', to:"microposts#new"
  get  '/signup',  to: 'users#new'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
   member do
    get :following, :followers
    end
  end
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts do
   resources :likes, only: [:new, :create, :destory]
   resources :comments, only: [:index, :create, :destroy], shallow: true
  end 
end

app/views/layouts/_footer.html.erb
<footer>
 <% if logged_in? %>
  <div class="container">
  <%= link_to "投稿", "/upload", id: "logo" ,class: "btn btn-primary"%>
  </div>
  <% end %>  
</footer>

app/views/layouts/_head.html.erb
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "InstagramClone", '/', id: "logo" %>
    <nav>
    <ul class="nav navbar-nav navbar-right">
  　<% if logged_in? %>
      <li><%= link_to "ユーザー一覧", users_path %></li>
      <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      アカウント <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
      <li><%= link_to "編集", edit_user_path(current_user) %></li>
      <li><%= link_to "パスワード再設定", "/password_resets/new" %></li>
      <li><%= link_to "ログアウト", logout_path, method: :delete  %></li>
      <li class="divider"></li>
      <li>
       <%= link_to "ユーザー削除",  user_path(current_user), method: :delete  %>
      </li>
      </ul>
      </li>
    <% else %>      
      <li><%= link_to "新規登録", signup_path %></li>
    <% end %>
    </ul>
 　 </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/head" %>
  <%= render 'layouts/shim' %>
 <body>
  <%= render 'layouts/header' %>
    <div class="container">
     <% flash.each do |message_type, message| %>
     <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>  
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
  
</html>